### ISSUE TITLE
How does Geckoboard differentiate data from diff sites configured in calibre?

### ISSUE THREAD

**Issue by karmakoder** [calibreapp/geckoboard#2]
I have a need to create different dashboards based on different sites that are configured in my calibre account? After following your instructions on this github project, am not sure where is the distinction made on the geckoboard side for specific site's dataset.
Do I need to create a new heroku app every time I need to see data from a new site on calibre?
If so, how do I create a gecko dashboard that shows the calibre dataset from a specific site?

**Comment by benschwarz** [comment]
Hey @karmakoder ! 

You can use a single heroku app to deliver data for each site in your account - Just a warning though, the last time I checked geckoboard has a limit of 5000 rows at any given time to be stored by it's "datatables". 

Metrics will be delivered to geckboard with unique 'slug' keys for each site, page & test profile. Each chart can be filtered by these parameters. 

If you'd like to discuss account information or want to have me cast an eye over your geckoboard account, please feel free to write to our support email. Happy to help! 👍

**Comment by karmakoder** [comment]
Hello @benschwarz . Thx for the quick response. Where do I see these slugs? Been poking around all over the place. If it helps this is the dashboard where am trying to filter data from 2 diff calibre sites : https://app.geckoboard.com/edit/dashboards/284096
Many thx

**Comment by karmakoder** [comment]
@benschwarz I found the place in geckodashboard settings where I can filter based on the site name. Is there any way to differentiate(different color scheme for diff sites) data from multiple sites on a single dashboard? This is our main use case for which we are evaluating gecko dashboard and would be great if you can confirm the possibility of achieving this. To be very clear, my ask is to be able to combine these 3 dashboards' data on a single dashboard:
https://app.geckoboard.com/edit/dashboards/284403
https://app.geckoboard.com/edit/dashboards/284096
https://app.geckoboard.com/edit/dashboards/284407

**Comment by GeckoLisa** [comment]
Hi there @karmakoder,

While I can't help with your questions about Calibre as the team there maintain this integration, I can help with the question about colours. We aren't able to offer multiple colour schemes on the same dashboard or the ability to colour-code particular widgets outside of showing where they are above or below particular metric values.

Would something like [a dashboard loop](https://support.geckoboard.com/hc/en-us/articles/203233027) with each individual dashboard a different colour work for you?  This way, you could view these three dashboards from a single URL and the background colour would help you differentiate. You would need a subscription including the Customization options for this. 

One other thing to note is that it is not possible for anyone outside of your subscription to access your dashboards so, although you have shared links here, we're not able to access them. If you would like someone to take a look at your dashboard without adding them to your subscription, you can give view-only access [by generating a sharing link](https://support.geckoboard.com/hc/en-us/articles/202333706).

I hope this is helpful!

Lisa
